### ISSUE TITLE
pwa not working on subroutes

### ISSUE THREAD

**Issue by AgentChris** [ragingwind/pwa-react-boilerplate#9]
steps to reproduce

yarn install
yarn run build
yarn start --env.sw

go to http://localhost:8080

disable network in chrome

go to http://localhost:8080/#/contact

then hit refresh

everthing crash

but if i go back to http://localhost:8080 it work

**Comment by ragingwind** [comment]
This project wasn't maintained any more. Please use create-react-app which well supports PWA features
